-- Add temp_password column to store the initial generated password for admin reference
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS temp_password text;

COMMENT ON COLUMN public.profiles.temp_password IS 'Temporary password generated by admin for initial business login';
